"""gen_header.py — emit firmware/include/riscq.h from contract.py (docs/software/02 §3c).

The C constants and the Python SocConfig are then literally the same numbers. Run as
`python -m riscq.gen_header [out_path]`; defaults to ../../firmware/include/riscq.h.
"""

import os
import sys

from . import contract as C


def render() -> str:
    """The canonical MMIO header. Addresses come from contract.py — never hand-edit riscq.h."""
    return f"""\
/* riscq.h — canonical MMIO header for a riscq core.
 *
 * GENERATED by python/riscq/gen_header.py from contract.py — DO NOT EDIT BY HAND.
 * Addresses + packing are the docs/software/01 hardware contract; every 16-bit DSP field is placed
 * at bus bits [{C.FIELD_BIT_OFFSET + 15}:{C.FIELD_BIT_OFFSET}] (stored word = code<<{C.FIELD_BIT_OFFSET}); startTime/fire are written low.
 */
#ifndef RISCQ_H
#define RISCQ_H
#include <stdint.h>

/* ── (1) bases & packing ─────────────────────────────────────────────────────────────────── */
#define RF_BASE      {C.RF_BASE:#06x}u            /* gate={C.RF_BASE:#x} readout={C.RF_BASE + C.RF_STRIDE:#x} demod={C.RF_BASE + 2 * C.RF_STRIDE:#x} decoder={C.RF_BASE + 3 * C.RF_STRIDE:#x} */
#define RF_STRIDE    {C.RF_STRIDE:#08x}u
#define GATE   {C.GATE}u
#define RDRV   {C.RDRV}u                        /* buffer selector → base = RF_BASE + buf*RF_STRIDE */
#define mmio(a)        (*(volatile uint32_t*)(uintptr_t)(a))
#define pack16(code)   ((uint32_t)((code) & 0xffff) << {C.FIELD_BIT_OFFSET})

/* ── (2) pulse-drive API (gate + readout-drive buffers) ──────────────────────────────────────
 * table entry slot s lives at (s+1)*{C.PULSE_TABLE_BASE:#x}; slot 0 is +{C.PULSE_TABLE_BASE:#x} (avoids the fire/freq aliases). */
static inline void set_freq (unsigned buf, int code)            {{ mmio(RF_BASE+buf*RF_STRIDE+{C.PULSE_FREQ:#x})                      = pack16(code); }}
static inline void set_phase(unsigned buf, unsigned s, int code){{ mmio(RF_BASE+buf*RF_STRIDE+(s+1)*{C.PULSE_TABLE_BASE:#x}+{C.PULSE_PHASE:#x}) = pack16(code); }}
static inline void set_amp  (unsigned buf, unsigned s, int code){{ mmio(RF_BASE+buf*RF_STRIDE+(s+1)*{C.PULSE_TABLE_BASE:#x}+{C.PULSE_AMP:#x}) = pack16(code); }}
static inline void set_env  (unsigned buf, unsigned s, int line){{ mmio(RF_BASE+buf*RF_STRIDE+(s+1)*{C.PULSE_TABLE_BASE:#x}+{C.PULSE_ENV:#x}) = pack16(line); }}
static inline void set_dur  (unsigned buf, unsigned s, int n)   {{ mmio(RF_BASE+buf*RF_STRIDE+(s+1)*{C.PULSE_TABLE_BASE:#x}+{C.PULSE_DUR:#x}) = pack16(n);    }}
static inline void set_start_time(unsigned buf, uint32_t t)     {{ mmio(RF_BASE+buf*RF_STRIDE+{C.PULSE_START_TIME:#x})                  = t;            }} /* full 32-bit */
static inline void fire(unsigned buf, unsigned slot)            {{ mmio(RF_BASE+buf*RF_STRIDE+{C.PULSE_FIRE:#x})                      = slot;         }} /* index, low bits */

/* ── (3) demod / decoder / control / readout / time (control block is plain 32-bit; noted reads HALT) */
static inline void set_demod(int f, int p)  {{ mmio({C.RF_BASE + 2 * C.RF_STRIDE + C.DEMOD_FREQ:#x}) = pack16(f); mmio({C.RF_BASE + 2 * C.RF_STRIDE + C.DEMOD_PHASE:#x}) = pack16(p); }}
static inline void arm_readout(uint32_t t, int dur){{ mmio({C.RF_BASE + 3 * C.RF_STRIDE + C.DECODER_START_TIME:#x})=t; mmio({C.RF_BASE + 3 * C.RF_STRIDE + C.DECODER_DUR:#x})=pack16(dur); }} /* dur write clears+arms the result */

static inline uint32_t now(void)             {{ return mmio({C.CPU_TIME:#x}); }}                  /* current batch time */
static inline void     sleep_until(uint32_t t){{ mmio({C.CPU_TIME_CMP:#x})=t; (void)mmio({C.CPU_WAIT_TIME_CMP:#x}); }} /* timeCmp, then halting waitTimeCmp */
static inline uint32_t from_host(void)       {{ return mmio({C.CPU_FROM_HOST:#x}); }}

static inline int  read_res (void) {{ return (int)mmio({C.CPU_RES:#x}); }}   /* HALTS until the integral settles; sign of I */
static inline int  read_real(void) {{ return (int)mmio({C.CPU_REAL:#x}); }}
static inline int  read_imag(void) {{ return (int)mmio({C.CPU_IMAG:#x}); }}

/* ── (4) result return: leave readout where the host reads it back over AXI (docs/software/02 §7) ── */
#define RESULT_ADDR  ({C.CPU_RAM_BASE:#x}u + {C.RESULT_OFFSET:#x}u)
static inline void put_result(int real, int imag, int res) {{
  mmio(RESULT_ADDR+{C.RESULT_REAL:#x}) = (uint32_t)real;
  mmio(RESULT_ADDR+{C.RESULT_IMAG:#x}) = (uint32_t)imag;
  mmio(RESULT_ADDR+{C.RESULT_RES:#x})  = (uint32_t)res;
  mmio(RESULT_ADDR+{C.RESULT_DONE:#x}) = 1u;            /* written last; host polls this for done */
}}

#endif /* RISCQ_H */
"""


def write_header(out_path: str) -> str:
    text = render()
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(text)
    return out_path


def _default_out() -> str:
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, "..", "..", "firmware", "include", "riscq.h"))


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else _default_out()
    print("wrote", write_header(out))
