"""IR -> C (spec 02 §4): a single readable main.c.

Unbound params become `volatile int32_t RQ_PARAM name = 0;` globals and input Arrays
`volatile int32_t name[N] RQ_PARAM = {0};` — RQ_PARAM pins them into .data so pre-run host
writes survive start.S zeroing .bss (the M1 gotcha). Each live ParamTable becomes a
host-retunable `.data` `volatile struct rq_slot name[count] RQ_PARAM = {0};` (riscq.run fills
it). Output Arrays are plain `.bss` globals (the kernel writes them). Locals are int32_t
(pointers: volatile int32_t *); control flow maps 1:1; calls emit verbatim by name. There is
NO compiler-injected prologue — main() opens with exactly what the kernel wrote (its own
init_pulse_params / set_freq calls), then the body, then `return 0` (start.S publishes DONE).
A #line directive before every statement maps gcc diagnostics to the kernel's python source.
"""

from __future__ import annotations

from riscq.lang import ir

_COP = {"and": "&&", "or": "||", "//": "/"}
_PREC = {"or": 1, "and": 2, "|": 3, "^": 4, "&": 5, "==": 6, "!=": 6,
         "<": 7, "<=": 7, ">": 7, ">=": 7, "<<": 8, ">>": 8,
         "+": 9, "-": 9, "*": 10, "//": 10, "%": 10}
_ATOM = 99  # operand slot that accepts only atoms unparenthesized


def emit(kir: ir.KernelIR) -> str:
    return _Emitter(kir).emit()


class _Emitter:
    def __init__(self, kir: ir.KernelIR):
        self.k = kir
        self.lines: list[str] = []

    def emit(self) -> str:
        k, w = self.k, self.lines.append
        w(f"/* GENERATED by riscq.lang from @kernel '{k.name}' "
          f"({k.src_file}:{k.def_line}) — do not edit. */")
        w('#include "riscq.h"')
        for h in k.includes:
            w(f'#include "{h}"')
        w("")
        if k.params:
            w("/* runtime parameters — host-written by name; RQ_PARAM pins them into .data */")
            for n in k.params:
                w(f"volatile int32_t RQ_PARAM {n} = 0;")
        if k.tables:
            w("/* pulse tables (.data, host-retunable by name) — filled by riscq.run */")
            for t in k.tables:
                w(f"volatile struct rq_slot {t.name}[{t.count}] RQ_PARAM = {{0}};")
        inputs = [(n, s) for n, s in k.arrays.items() if n in k.input_arrays]
        outputs = [(n, s) for n, s in k.arrays.items() if n not in k.input_arrays]
        if inputs:
            w("/* input arrays (.data) — host-preloaded by name; RQ_PARAM survives boot */")
            for n, size in inputs:
                w(f"volatile int32_t {n}[{size}] RQ_PARAM = {{0}};")
        if outputs:
            w("/* result arrays (.bss) — host-read by name */")
            for n, size in outputs:
                w(f"volatile int32_t {n}[{size}];")
        w("")
        w("int main(void) {")
        for n, ty in k.locals.items():
            w(f"    volatile int32_t *{n};" if ty == "ptr" else f"    int32_t {n};")
        if k.locals:
            w("")
        for s in k.body:
            self.stmt(s, 1)
        w("")
        w("    return 0;")
        w("}")
        return "\n".join(self.lines) + "\n"

    # ── statements ──

    def _mark(self, line: int):
        self.lines.append(f'#line {line} "{self.k.src_file}"')

    def stmt(self, s, ind: int):
        pad = "    " * ind
        w = self.lines.append
        self._mark(s.line)
        if isinstance(s, ir.Assign):
            w(f"{pad}{self.ex(s.target)} = {self.ex(s.value)};")
        elif isinstance(s, ir.CallStmt):
            w(f"{pad}{self.ex(s.call)};")
        elif isinstance(s, ir.For):
            v = s.var.name
            if isinstance(s.step, ir.Const):
                cmp = "<" if s.step.value > 0 else ">"
                cond = f"{v} {cmp} {self.ex(s.stop, 8)}"
            else:  # runtime step: direction decided per evaluation, like the bounds
                cond = (f"{self.ex(s.step, 8)} >= 0 ? {v} < {self.ex(s.stop, 8)} "
                        f": {v} > {self.ex(s.stop, 8)}")
            w(f"{pad}for ({v} = {self.ex(s.start)}; {cond}; {v} += {self.ex(s.step)}) {{")
            self.block(s.body, ind + 1)
            w(f"{pad}}}")
        elif isinstance(s, ir.While):
            w(f"{pad}while ({self.ex(s.cond)}) {{")
            self.block(s.body, ind + 1)
            w(f"{pad}}}")
        elif isinstance(s, ir.If):
            w(f"{pad}if ({self.ex(s.cond)}) {{")
            self.block(s.then, ind + 1)
            if s.orelse:
                w(f"{pad}}} else {{")
                self.block(s.orelse, ind + 1)
            w(f"{pad}}}")
        elif isinstance(s, ir.Break):
            w(f"{pad}break;")
        elif isinstance(s, ir.Continue):
            w(f"{pad}continue;")
        else:
            raise AssertionError(f"unknown IR statement {s!r}")

    def block(self, stmts, ind: int):
        for s in stmts:
            self.stmt(s, ind)

    # ── expressions (prec = the binding strength the context requires) ──

    def ex(self, e, prec: int = 0) -> str:
        if isinstance(e, ir.Const):
            if e.cname:
                return e.cname
            return f"({e.value})" if e.value < 0 and prec > 0 else str(e.value)
        if isinstance(e, (ir.Var, ir.Param, ir.ArrayRef, ir.TableRef)):
            return e.name
        if isinstance(e, ir.Index):
            return f"{self.ex(e.base, _ATOM)}[{self.ex(e.index)}]"
        if isinstance(e, ir.PtrOf):
            if e.offset is None:
                return e.array
            s = f"{e.array} + {self.ex(e.offset, 10)}"
            return f"({s})" if prec > 9 else s
        if isinstance(e, ir.Not):
            return f"!{self.ex(e.operand, _ATOM)}"
        if isinstance(e, ir.BinOp):
            p = _PREC[e.op]
            s = f"{self.ex(e.lhs, p)} {_COP.get(e.op, e.op)} {self.ex(e.rhs, p + 1)}"
            return f"({s})" if p < prec else s
        if isinstance(e, ir.Call):
            return f"{e.name}({', '.join(self.ex(a) for a in e.args)})"
        raise AssertionError(f"unknown IR expression {e!r}")
