"""The single Driver seam: 4 methods, everything above is backend-agnostic."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class Driver(Protocol):
    def read32(self, addr: int) -> int: ...
    def write32(self, addr: int, value: int) -> None: ...
    def read_block(self, addr: int, nbytes: int) -> bytes: ...
    def write_block(self, addr: int, data: bytes) -> None: ...
