"""sweep.py — a sweep is an on-core arithmetic loop, not an uploaded table (specs 02 §3, 00-contracts §2).

The host converts the linspace endpoints to codes once and emits a tiny fixed-point descriptor
(`acc0, inc, n`); the core walks the grid by repeated addition (`acc >> FRAC` is the code, `acc += inc`
advances it — the DDS/Bresenham trick), so a re-run just rewrites a handful of words. The host fits
against the **realized** codes by reproducing the same integer recurrence, so the x-axis is exact.

`Sweep2D` is the Ramsey case: detuning × delay, whose Rz phase `φ(δ,τ)=2π·δ·τ` is bilinear, so the grid
is nested forward differences (pure addition, no multiply ⇒ plain RV32I).
"""

from dataclasses import dataclass
from math import pi

import numpy as np

from ..program import FRAC, Apply
from ..socconfig import SocConfig

# target → (the SocConfig code converter, the inverse code→physical map) and the per-point register.
_CONV = {
    "readout.freq": "freq2code", "demod.freq": "freq2code",
    "readout.amp": "amp2code", "drive.amp": "amp2code", "drive.phase": "phase2code",
}


def _to_phys(cfg: SocConfig, target: str, code: int) -> float:
    """Invert a code back to physical units for the fit x-axis / plots."""
    conv = _CONV[target]
    if conv == "freq2code":
        return code * cfg.fs / 2 ** 16
    if conv == "amp2code":
        return code / 2 ** 15
    return code / 2 ** 15 * pi               # phase2code


@dataclass
class Sweep:
    """A 1-D linspace sweep of one register (00-contracts §3). `slot` is filled by the sequence
    lowering for the drive.amp/drive.phase targets (which gate slot the sweep drives)."""
    target: str                              # readout.freq | demod.freq | readout.amp | drive.amp | drive.phase
    start: float
    stop: float
    n: int
    slot: int = 0

    def __post_init__(self):
        if self.target not in _CONV:
            raise ValueError(f"unknown sweep target {self.target!r} (expected one of {list(_CONV)})")

    # ── codes / descriptor ──────────────────────────────────────────────────────────────────────
    def _code(self, cfg: SocConfig, value: float) -> int:
        return getattr(cfg, _CONV[self.target])(value)

    def _acc0_inc(self, cfg: SocConfig):
        c0, c1 = self._code(cfg, self.start), self._code(cfg, self.stop)
        acc0 = c0 << FRAC
        inc = 0 if self.n <= 1 else round(((c1 - c0) << FRAC) / (self.n - 1))
        return acc0, inc

    def descriptor_words(self, cfg: SocConfig) -> list:
        """The host-written SWEEP header: [n, acc0, inc] (signed ints; Soc masks on write)."""
        acc0, inc = self._acc0_inc(cfg)
        return [self.n, acc0, inc]

    def realized_codes(self, cfg: SocConfig) -> np.ndarray:
        """The codes the core actually applies — the recurrence `(acc0 + p·inc) >> FRAC`, reproduced
        exactly (Python `>>` floors like the core's int32 arithmetic shift)."""
        acc0, inc = self._acc0_inc(cfg)
        return np.array([(acc0 + p * inc) >> FRAC for p in range(self.n)], dtype=np.int64)

    def realized_values(self, cfg: SocConfig) -> np.ndarray:
        """The realized x-axis in physical units (Hz / amplitude / rad)."""
        return np.array([_to_phys(cfg, self.target, int(c)) for c in self.realized_codes(cfg)])

    # ── the per-point on-core write ─────────────────────────────────────────────────────────────
    def apply(self) -> Apply:
        if self.target in ("readout.freq", "demod.freq"):
            return Apply(reg="demod")
        if self.target == "readout.amp":
            return Apply(reg="amp", buf="RDRV", slot=0)
        if self.target == "drive.amp":
            return Apply(reg="amp", buf="GATE", slot=self.slot)
        return Apply(reg="phase", buf="GATE", slot=self.slot)        # drive.phase


@dataclass
class Sweep2D:
    """Ramsey: detuning (outer) × delay (inner). The bilinear Rz phase `φ(δ,τ)=2π·δ·τ` is generated by
    nested forward differences (00-contracts §2); `phase_slot` is the 2nd-x90 slot the kernel drives."""
    det_start: float
    det_stop: float
    n_det: int
    del_start: float
    del_stop: float
    n_del: int
    phase_slot: int = 0

    def _det_step(self):
        d0 = self.det_start
        dd = 0.0 if self.n_det <= 1 else (self.det_stop - self.det_start) / (self.n_det - 1)
        return d0, dd

    def _delay_batches(self, cfg: SocConfig):
        """The on-core delay axis in batches: tau0 + i·dtau (quantized — the phase seeds key off this so
        the Rz tracks the *realized* idle, not the intended continuous one)."""
        t0b = cfg.s2batch(self.del_start)
        dtb = 0 if self.n_del <= 1 else cfg.s2batch((self.del_stop - self.del_start) / (self.n_del - 1))
        return t0b, dtb

    def descriptor_words(self, cfg: SocConfig) -> list:
        """[n_det, n_del, tau0, dtau, S, dS, D, dD] — the delay (batch) axis + the bilinear-phase seeds.

        Phase codes are NOT clamped: a Ramsey phase spans many turns, and the hardware phase register
        wraps mod 2^16 at the set_phase write, so the seeds are plain round(rad/π·2^15). They key off the
        *quantized* delay (tau in batches → seconds) so φ matches the idle the qubit actually sees."""
        d0, dd = self._det_step()
        t0b, dtb = self._delay_batches(cfg)
        tau0_s, dtau_s = t0b * cfg.batch_size / cfg.fs, dtb * cfg.batch_size / cfg.fs
        wrap = lambda rad: round(rad / pi * 2 ** 15)        # wraps at the 16-bit write (no clamp)
        return [self.n_det, self.n_del, t0b, dtb,
                wrap(2 * pi * d0 * tau0_s), wrap(2 * pi * dd * tau0_s),
                wrap(2 * pi * d0 * dtau_s), wrap(2 * pi * dd * dtau_s)]

    def realized_detunings(self) -> np.ndarray:
        return np.linspace(self.det_start, self.det_stop, self.n_det)

    def realized_delays(self, cfg: SocConfig) -> np.ndarray:
        """The realized delay axis in seconds (the on-core `tau0 + i·dtau` batches → seconds)."""
        t0b, dtb = self._delay_batches(cfg)
        return np.array([(t0b + i * dtb) * cfg.batch_size / cfg.fs for i in range(self.n_del)])
