/* riscq.h — canonical MMIO header for a riscq core.
 *
 * GENERATED by python/riscq/gen_header.py from contract.py — DO NOT EDIT BY HAND.
 * Addresses + packing are the docs/software/01 hardware contract; every 16-bit DSP field is placed
 * at bus bits [31:16] (stored word = code<<16); startTime/fire are written low.
 */
#ifndef RISCQ_H
#define RISCQ_H
#include <stdint.h>

/* ── (1) bases & packing ─────────────────────────────────────────────────────────────────── */
#define RF_BASE      0x10000u            /* gate=0x10000 readout=0x20000 demod=0x30000 decoder=0x40000 */
#define RF_STRIDE    0x010000u
#define GATE   0u
#define RDRV   1u                        /* buffer selector → base = RF_BASE + buf*RF_STRIDE */
#define mmio(a)        (*(volatile uint32_t*)(uintptr_t)(a))
#define pack16(code)   ((uint32_t)((code) & 0xffff) << 16)

/* ── (2) pulse-drive API (gate + readout-drive buffers) ──────────────────────────────────────
 * table entry slot s lives at (s+1)*0x10; slot 0 is +0x10 (avoids the fire/freq aliases). */
static inline void set_freq (unsigned buf, int code)            { mmio(RF_BASE+buf*RF_STRIDE+0x4)                      = pack16(code); }
static inline void set_phase(unsigned buf, unsigned s, int code){ mmio(RF_BASE+buf*RF_STRIDE+(s+1)*0x10+0x0) = pack16(code); }
static inline void set_amp  (unsigned buf, unsigned s, int code){ mmio(RF_BASE+buf*RF_STRIDE+(s+1)*0x10+0x4) = pack16(code); }
static inline void set_env  (unsigned buf, unsigned s, int line){ mmio(RF_BASE+buf*RF_STRIDE+(s+1)*0x10+0x8) = pack16(line); }
static inline void set_dur  (unsigned buf, unsigned s, int n)   { mmio(RF_BASE+buf*RF_STRIDE+(s+1)*0x10+0xc) = pack16(n);    }
static inline void set_start_time(unsigned buf, uint32_t t)     { mmio(RF_BASE+buf*RF_STRIDE+0x4100)                  = t;            } /* full 32-bit */
static inline void fire(unsigned buf, unsigned slot)            { mmio(RF_BASE+buf*RF_STRIDE+0x0)                      = slot;         } /* index, low bits */

/* ── (3) demod / decoder / control / readout / time (control block is plain 32-bit; noted reads HALT) */
static inline void set_demod(int f, int p)  { mmio(0x30000) = pack16(f); mmio(0x30004) = pack16(p); }
static inline void arm_readout(uint32_t t, int dur){ mmio(0x44100)=t; mmio(0x40000)=pack16(dur); } /* dur write clears+arms the result */

static inline uint32_t now(void)             { return mmio(0xbff8); }                  /* current batch time */
static inline void     sleep_until(uint32_t t){ mmio(0x4000)=t; (void)mmio(0x4008); } /* timeCmp, then halting waitTimeCmp */
static inline uint32_t from_host(void)       { return mmio(0x2000); }

static inline int  read_res (void) { return (int)mmio(0x4200); }   /* HALTS until the integral settles; sign of I */
static inline int  read_real(void) { return (int)mmio(0x4204); }
static inline int  read_imag(void) { return (int)mmio(0x4208); }

/* ── (4) result return: leave readout where the host reads it back over AXI (docs/software/02 §7) ── */
#define RESULT_ADDR  (0x80000000u + 0x400u)
static inline void put_result(int real, int imag, int res) {
  mmio(RESULT_ADDR+0x0) = (uint32_t)real;
  mmio(RESULT_ADDR+0x4) = (uint32_t)imag;
  mmio(RESULT_ADDR+0x8)  = (uint32_t)res;
  mmio(RESULT_ADDR+0xc) = 1u;            /* written last; host polls this for done */
}

#endif /* RISCQ_H */
