// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VTOP__SYMS_H_
#define VERILATED_VTOP__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "Vtop.h"

// INCLUDE MODULE CLASSES
#include "Vtop___024root.h"
#include "Vtop_PulseGenerator.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES) Vtop__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    Vtop* const __Vm_modelp;
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    Vtop___024root                 TOP;
    Vtop_PulseGenerator            TOP__PulseTableSoc__DOT__riscqArea_riscqCores_0_posted_gateChannel__DOT__pulseGenerator_3;
    Vtop_PulseGenerator            TOP__PulseTableSoc__DOT__riscqArea_riscqCores_0_posted_roChannel__DOT__pulseGenerator_3;

    // SCOPE NAMES
    VerilatedScope* __Vscopep_PulseTableSoc;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_down_arbiter_core;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_down_arbiter_core__a_arbiter;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_read_bridge;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_read_bridge__aligner;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_read_bridge__compactor;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_read_bridge__onPerId_bridge;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_read_bridge__toTileink;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_write_bridge;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_write_bridge__aligner;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_write_bridge__compactor;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_write_bridge__compactor__io_up_aw_fork2;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_write_bridge__onPerId_bridge;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_write_bridge__onPerId_bridge__onAw_halted_fork2;
    VerilatedScope* __Vscopep_PulseTableSoc__bridge_write_bridge__toTileink;
    VerilatedScope* __Vscopep_PulseTableSoc__hostBus_decoder_core;
    VerilatedScope* __Vscopep_PulseTableSoc__hostBus_decoder_core__d_arbiter;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_decoderRd;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_decoderRd__muls_0;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_decoderRd__muls_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_decoderRd__muls_2;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_decoderRd__muls_3;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_demodMemFiber_ramFibers_0_fiber_thread_logic;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_demodMemFiber_rams_0;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_demodMemFiber_rams_0__bram_4;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_demodMemFiber_rams_0__bram_4__output_register;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__buf_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__addrQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__addrQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__ampQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__ampQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__carrierGen;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__carrierGen__cordic_6;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__carrierGen__muls_0;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__carrierGen__muls_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__carrierGen__muls_2;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__carrierGen__muls_3;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__durQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__durQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__envMuls_0;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__envMuls_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__envMuls_2;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__envMuls_3;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__envReader;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__freqCQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__freqCQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__freqPQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__freqPQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__phaseQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__phaseQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__phasorGen;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_demodChannel__pg__phasorGen__cordic_6;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__buf_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__addrQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__addrQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__ampQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__ampQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__cordic_6;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_0;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_10;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_11;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_12;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_13;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_14;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_15;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_2;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_3;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_4;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_5;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_6;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_7;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_8;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__carrierGen__muls_9;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__durQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__durQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_0;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_10;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_11;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_12;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_13;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_14;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_15;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_2;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_3;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_4;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_5;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_6;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_7;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_8;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envMuls_9;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__envReader;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__freqCQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__freqCQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__freqPQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__freqPQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__phaseQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__phaseQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__phasorGen;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_gateChannel__pulseGenerator_3__phasorGen__cordic_6;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__buf_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__addrQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__addrQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__ampQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__ampQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__cordic_6;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_0;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_10;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_11;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_12;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_13;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_14;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_15;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_2;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_3;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_4;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_5;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_6;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_7;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_8;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__carrierGen__muls_9;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__durQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__durQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_0;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_10;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_11;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_12;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_13;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_14;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_15;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_2;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_3;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_4;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_5;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_6;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_7;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_8;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envMuls_9;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__envReader;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__freqCQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__freqCQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__freqPQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__freqPQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__phaseQ;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__phaseQ__logic_fifo;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__phasorGen;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_posted_roChannel__pulseGenerator_3__phasorGen__cordic_6;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_pulseMemFiber_ramFibers_0_fiber_thread_logic;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_pulseMemFiber_rams_0;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_pulseMemFiber_rams_0__bram_4;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_pulseMemFiber_rams_0__bram_4__output_register;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_readoutMemFiber_ramFibers_0_fiber_thread_logic;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_readoutMemFiber_rams_0;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_readoutMemFiber_rams_0__bram_4;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_readoutMemFiber_rams_0__bram_4__output_register;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__dBusFiber_thread_logic;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__dMemPortDec_decoder_core;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__dMemPortDec_decoder_core__d_arbiter;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__dataMemBusToTilelink_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__iBusFiber_thread_logic;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__iMemPortArb_arbiter_core;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__iMemPortArb_arbiter_core__a_arbiter;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__mem;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__mem__uram_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__postedStoreShim_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__postedStoreShim_1__sbuf;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqArea_riscqCores_0_riscvSoc__riscqFiber_riscq;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqMemBus_to_riscqArea_riscqCores_0_iMemLoad_up_cc;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqMemBus_to_riscqArea_riscqCores_0_iMemLoad_up_cc__a_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqMemBus_to_riscqArea_riscqCores_0_iMemLoad_up_cc__a_1__popToPushGray_buffercc;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqMemBus_to_riscqArea_riscqCores_0_iMemLoad_up_cc__a_1__pushToPopGray_buffercc;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqMemBus_to_riscqArea_riscqCores_0_iMemLoad_up_cc__a_1__reset_asyncAssertSyncDeassert_buffercc;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqMemBus_to_riscqArea_riscqCores_0_iMemLoad_up_cc__d_1;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqMemBus_to_riscqArea_riscqCores_0_iMemLoad_up_cc__d_1__popToPushGray_buffercc;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqMemBus_to_riscqArea_riscqCores_0_iMemLoad_up_cc__d_1__pushToPopGray_buffercc;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqMemBus_to_riscqArea_riscqCores_0_iMemLoad_up_cc__d_1__riscqMemBus_to_riscqArea_riscqCores_0_iMemLoad_up_cc_toplevel_dspRst_asyncAssertSyncDeassert_buffercc;
    VerilatedScope* __Vscopep_PulseTableSoc__riscqResetHostCd_buffercc;
    VerilatedScope* __Vscopep_PulseTableSoc__robAdapter_logic_bridge;
    VerilatedScope* __Vscopep_PulseTableSoc__robAdapter_logic_bridge__upsize_d_ctx;
    VerilatedScope* __Vscopep_PulseTableSoc__robs_ramFibers_0_ramFiber_thread_logic;
    VerilatedScope* __Vscopep_PulseTableSoc__robs_rams_0;
    VerilatedScope* __Vscopep_PulseTableSoc__robs_rams_0__bram_4;
    VerilatedScope* __Vscopep_PulseTableSoc__robs_rams_0__bram_4__output_register;
    VerilatedScope* __Vscopep_PulseTableSoc__timeOffset_buffercc;
    VerilatedScope* __Vscopep_TOP;

    // SCOPE HIERARCHY
    VerilatedHierarchy __Vhier;

    // CONSTRUCTORS
    Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp);
    ~Vtop__Syms();
    void Vtop__Syms__ctor__0();
    void Vtop__Syms__ctor__1();
    void Vtop__Syms__ctor__2();
    void Vtop__Syms__ctor__3();
    void Vtop__Syms__ctor__4();
    void Vtop__Syms__ctor__5();
    void Vtop__Syms__dtor__0();

    // METHODS
    const char* name() const { return TOP.vlNamep; }
};

#endif  // guard
